<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup Label="Build">
    <PackageVersion Include="MinVer" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup Label="Benchmark">
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <ItemGroup Label="Runtime">
    <PackageVersion Include="holonsoft.FluentConditions" Version="3.0.1" />
    <PackageVersion Include="holonsoft.FluentDateTime" Version="2.1.1" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup Label="Test">
    <PackageVersion Include="holonsoft.Utils" Version="1.10.1" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

</Project>
