<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LibraryTargetFrameworks)</TargetFrameworks>
    <Title>FastProtocolConverter by holonsoft</Title>
    <Description>Reflection based fast protocol converter: converts raw bytes (e. g. from a hardware device) to an instance of a class or vice versa.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="holonsoft.FluentConditions" />
    <PackageReference Include="holonsoft.FluentDateTime" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\holonsoft.FastProtocolConverter.Abstractions\holonsoft.FastProtocolConverter.Abstractions.csproj" />
  </ItemGroup>

</Project>
