<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <EnablePackageValidation>false</EnablePackageValidation>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="holonsoft.FluentDateTime" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\holonsoft.FastProtocolConverter.Abstractions\holonsoft.FastProtocolConverter.Abstractions.csproj">
      <Private>true</Private>
    </ProjectReference>
    <ProjectReference Include="..\holonsoft.FastProtocolConverter\holonsoft.FastProtocolConverter.csproj" />
  </ItemGroup>

</Project>
